export const tips: string[] = [
  "Don't forget to refresh the page if you feel that the data you have sent is missing.",
  "Always use capital letters if you want to trigger a command.",
  "Did you know that pressing the&nbsp;<kbd class='w-5 h-5 min-w-[20px] mx-3 rounded inline-flex items-center justify-center uppercase bg-gradient-to-tl bg-white from-slate-200 dark:from-[#565872] dark:to-[#31355b]'>⌘</kbd><kbd class='w-5 h-5 min-w-[20px] mx-3 rounded inline-flex items-center justify-center uppercase bg-gradient-to-tl bg-white from-slate-200 dark:from-[#565872] dark:to-[#31355b]'>⇧</kbd><kbd class='w-5 h-5 min-w-[20px] mx-3 rounded inline-flex items-center justify-center uppercase bg-gradient-to-tl bg-white from-slate-200 dark:from-[#565872] dark:to-[#31355b]'>K</kbd>&nbsp;keys simultaneously triggers a list of commands dialog?",
  "Consider trying dark mode for a new eye-pleasing sensation at night.",
  "Press&nbsp;<kbd class='w-5 h-5 min-w-[20px] mx-3 rounded inline-flex items-center justify-center uppercase bg-gradient-to-tl bg-white from-slate-200 dark:from-[#565872] dark:to-[#31355b]'>⌘</kbd><kbd class='w-5 h-5 min-w-[20px] mx-3 rounded inline-flex items-center justify-center uppercase bg-gradient-to-tl bg-white from-slate-200 dark:from-[#565872] dark:to-[#31355b]'>⇧</kbd><kbd class='w-5 h-5 min-w-[20px] mx-3 rounded inline-flex items-center justify-center uppercase bg-gradient-to-tl bg-white from-slate-200 dark:from-[#565872] dark:to-[#31355b]'>Z</kbd>&nbsp;to change the page theme.",
  "Don't forget to always include my name in your cloned projects and consider tagging my github account as well.",
  "Did you know that the symbol&nbsp;<kbd class='w-5 h-5 min-w-[20px] mx-3 rounded inline-flex items-center justify-center uppercase bg-gradient-to-tl bg-white from-slate-200 dark:from-[#565872] dark:to-[#31355b]'>⌘</kbd>&nbsp;is a command in MacOS or control ( CTRL ) in Windows?",
  "Feel free to create new issues, discussions or even pull requests for better improvements.",
  "Did you know that the symbol&nbsp;<kbd class='w-5 h-5 min-w-[20px] mx-3 rounded inline-flex items-center justify-center uppercase bg-gradient-to-tl bg-white from-slate-200 dark:from-[#565872] dark:to-[#31355b]'>⇧</kbd>&nbsp;is pronounced SHIFT?",
  "Always consider using a Virtual Private Network (VPN) to mask your identity and make it more complex and difficult to track.",
];